# Generated by Django 3.1.7 on 2021-03-08 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_snippet_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='user',
            new_name='owner',
        ),
    ]
